### ISSUE TITLE
Some data possibliy missing?

### ISSUE THREAD

**Issue by Postroggy** [seitlab/Glint#1]
as I run the code to build the dataset.  

In  `ifttt_build_dataset`  when I run `build_ifttt_graph.py` program crashes and I found `graph_properties.csv`  file does not have graph_id=`9355` data while `graph_edge.csv` have. so I wonder if there is some data missing in [graph_properties.csv](https://github.com/seitlab/Glint/blob/a058d470a5c6dcc6d1a8bda671d06bb12c1f358f/ifttt_build_dataset/graph_properties.csv?plain=1#L9357) 

in the `heterograph_dataset` folder, `alexa_interact_alexa.csv` have graph_id=`12758`, but  [graph_properties.csv](https://github.com/seitlab/Glint/blob/a058d470a5c6dcc6d1a8bda671d06bb12c1f358f/heterograph_dataset/graph_properties.csv?plain=1#L12760) do not have the data of graph_id=`12758` (the last graph_id is 1257).

so I deleted the graph data in other csv files that `graph_properties.csv` does not have to get the `build_dataset` program run and build `bin` files.

Could you check the data you provided again? Or maybe I was wrong, please let me know.

**Comment by MyRespect** [comment]
Hello, thank you so much for your attention! Yes, as you noticed, due to the version issue, there was an inconsistency between the edge files and the graph_properties file (e.g., missing 9355 and 12758) for the synthesized dataset. You can delete the related 9355 and 12758 graph info, please see updated.
